language: php

sudo: false

before_script:
  - travis_retry composer self-update --2
  - travis_retry composer install

script:
  - phpunit

matrix:
  include:
    - php: 7.3
    - php: 7.4
    - php: 8.0
