language: php

sudo: false

before_script:
  - travis_retry composer self-update
  - travis_retry composer install

script:
  - phpunit

matrix:
  include:
    - php: 7.1
    - php: 7.2
    - php: nightly
